### ISSUE TITLE
"pflags" variable in SR output giving wrong values

### ISSUE THREAD

**Issue by slhowardESR** [ICESat2-SlideRule/sliderule#357]
The pflags variable seems to have the wrong values in it. 

 pflags    should have values like:     
`  pflags                
           Size:       503586x1
           Dimensions: delta_time
           Datatype:   double
           Attributes:
                       long_name     = 'Processing Flags'
                       flag_values   = **[0  1  2  4]**
                       flag_meanings = 'valid, spread too short, too few photons, max iterations reached'
                       valid_min     = 0
                       valid_max     = 4
                       coordinates   = 'latitude longitude'`
 
But instead, when I read the output file,  I get:
![pflag](https://github.com/ICESat2-SlideRule/sliderule/assets/5480396/e9b725fc-8e76-4ff8-8092-b7a9d37ca679)

This is true in both netcdf and parquet files read in matlab.  (and it happens on both the released version, and the current main development branch.  And it is true for the tracks I have looked at .

I processed a small area at the end of Sept (with a current released version I think), and the pflags in that version were correct. 

Let me know if you need more info.

**Comment by jpswinski** [comment]
Turns out I introduced the bug into the code when making some changes to the atl06 code - the pflag variable was no longer being initialized and as a result, it was starting with garbage values before having the different flags OR'ed in.  I've made the fix and rebuilt the docker image.  You should be good to go with the `esr` cluster.
